on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.8-dev', '3.9', '3.9-dev', '3.10-dev']
        os: ['ubuntu-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: Python ${{ matrix.python }} on ${{ matrix.os }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python }} 
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install build
          pyproject-build --wheel --outdir dist .
          find dist -name "*.whl" | xargs pip3 install
          pip install flake8 pytest
      - name: Show python version and plugin package
        run: |
          python --version
          pip show sopel_plugins.pingpong
      - name: Run tests
        run: |
          flake8 sopel_pingpong/pingpong --max-line-length 265 --exclude=dist/*,build/*
          pytest tests
      - name: Run pip freeze
        run: |
          pip freeze
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel
        run: >-
          python -m
          build
          --wheel
          --outdir dist/
          .
      - name: Publish to PyPi
        if: github.event_name == 'push' && github.ref == 'refs/heads/release'
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_token }}
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
